### ISSUE TITLE
升到到v1.3.11版本就出现的错误

### ISSUE THREAD

**Issue by joyoes** [goflyfox/gmanager#11]
gtoken.go:397:41:not enough arguments in call to grand.Str
have(number)
want(string,int)
![111111111111](https://user-images.githubusercontent.com/16605854/76401500-ee39fa80-63bc-11ea-9d7e-f4ba62cf06cf.png)

**Comment by joyoes** [comment]
![2222222222222](https://user-images.githubusercontent.com/16605854/76401854-833cf380-63bd-11ea-8415-29900eb16bd8.png)
 我看了grand.Str()确实是需要传两个参数，而你这里只传了一个参数哈

**Comment by joyoes** [comment]
我用的是GF 1.11.5版本

**Comment by joyoes** [comment]
![3333333333333](https://user-images.githubusercontent.com/16605854/76403393-cef09c80-63bf-11ea-9736-b15bf8cb789b.png)
我自己修改成了这个样子，再次运行就正常了，不知道我这样修改对不对头哈

**Comment by zcool321** [comment]
建议改为grand.Letters,gtoken我马上发布 升级最新版本就好了
