### ISSUE TITLE
我直接下载了你的gmanger后，看到服务器端也设置了跨域设置，但还是出现这样的错误呢

### ISSUE THREAD

**Issue by joyoes** [goflyfox/gmanager#12]
![QQ图片20200615220235](https://user-images.githubusercontent.com/16605854/84666759-1012c280-af54-11ea-8f00-47cb00ac57af.png)
![2](https://user-images.githubusercontent.com/16605854/84667019-6122b680-af54-11ea-8351-6ff3f8869ed0.png)
![3](https://user-images.githubusercontent.com/16605854/84667028-63851080-af54-11ea-900d-aef0764710e9.png)
奇怪怎么还是会出现跨域的错误呢？

**Comment by zcool321** [comment]
你截图的问题和跨域没关系吧；跨域问题console会有两一个错误

**Comment by joyoes** [comment]
@zcool321 我暂时解决了，是直接把http改为https就正常了，请群主测试一下，但还有没有其他更好的办法吗？

**Comment by zcool321** [comment]
你的网站访问是https的吧？
